name: next-js-workflow-JobConcurrency

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    concurrency:
      group: deploy
      cancel-in-progress: true

    steps:
      - name: checkout repository
        uses: actions/checkout@v4.2.2

      - name: install dependencies
        run: npm install

      - name: build next js app
        run: npm run build

      - name: deploy app
        run: echo "depolying app"
        
        
